// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FlatFeature A flattened feature suitable for export to GIS.
// swagger:model FlatFeature
type FlatFeature struct {

	// geometry
	Geometry *LineString `json:"geometry,omitempty"`

	// properties
	Properties map[string]string `json:"properties,omitempty"`

	// type
	// Enum: [Feature]
	Type string `json:"type,omitempty"`
}

// Validate validates this flat feature
func (m *FlatFeature) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeometry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FlatFeature) validateGeometry(formats strfmt.Registry) error {

	if swag.IsZero(m.Geometry) { // not required
		return nil
	}

	if m.Geometry != nil {
		if err := m.Geometry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("geometry")
			}
			return err
		}
	}

	return nil
}

var flatFeatureTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Feature"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		flatFeatureTypeTypePropEnum = append(flatFeatureTypeTypePropEnum, v)
	}
}

const (

	// FlatFeatureTypeFeature captures enum value "Feature"
	FlatFeatureTypeFeature string = "Feature"
)

// prop value enum
func (m *FlatFeature) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, flatFeatureTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *FlatFeature) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FlatFeature) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlatFeature) UnmarshalBinary(b []byte) error {
	var res FlatFeature
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
