// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// NoCurbsReason If we did not return any curb segments, `no_curbs_reason` will contain a
// human-readable explanation of why (except for requests for data by curb ID, which return
// 404s instead).
//
// swagger:model NoCurbsReason
type NoCurbsReason string

// Validate validates this no curbs reason
func (m NoCurbsReason) Validate(formats strfmt.Registry) error {
	return nil
}
