// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SVLocationFeature A shared vehicle location, as a GeoJSON Feature.
// swagger:model SVLocationFeature
type SVLocationFeature struct {

	// geometry
	// Required: true
	Geometry *PointGeometry `json:"geometry"`

	// The ID of the location, set by the server. Currently, this is not a permanent value
	// - use `system_id` and `station_id` instead!
	//
	// Required: true
	ID *string `json:"id"`

	// properties
	// Required: true
	Properties *SVLocationFeatureProperties `json:"properties"`

	// type
	// Required: true
	// Enum: [Feature]
	Type *string `json:"type"`
}

// Validate validates this s v location feature
func (m *SVLocationFeature) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeometry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SVLocationFeature) validateGeometry(formats strfmt.Registry) error {

	if err := validate.Required("geometry", "body", m.Geometry); err != nil {
		return err
	}

	if m.Geometry != nil {
		if err := m.Geometry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("geometry")
			}
			return err
		}
	}

	return nil
}

func (m *SVLocationFeature) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *SVLocationFeature) validateProperties(formats strfmt.Registry) error {

	if err := validate.Required("properties", "body", m.Properties); err != nil {
		return err
	}

	if m.Properties != nil {
		if err := m.Properties.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("properties")
			}
			return err
		}
	}

	return nil
}

var sVLocationFeatureTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Feature"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sVLocationFeatureTypeTypePropEnum = append(sVLocationFeatureTypeTypePropEnum, v)
	}
}

const (

	// SVLocationFeatureTypeFeature captures enum value "Feature"
	SVLocationFeatureTypeFeature string = "Feature"
)

// prop value enum
func (m *SVLocationFeature) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, sVLocationFeatureTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SVLocationFeature) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SVLocationFeature) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SVLocationFeature) UnmarshalBinary(b []byte) error {
	var res SVLocationFeature
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
