// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SVLocationList A list of locations, as a GeoJSON FeatureCollection.
// swagger:model SVLocationList
type SVLocationList struct {

	// features
	// Required: true
	Features []*SVLocationFeature `json:"features"`

	// type
	// Required: true
	// Enum: [FeatureCollection]
	Type *string `json:"type"`
}

// Validate validates this s v location list
func (m *SVLocationList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SVLocationList) validateFeatures(formats strfmt.Registry) error {

	if err := validate.Required("features", "body", m.Features); err != nil {
		return err
	}

	for i := 0; i < len(m.Features); i++ {
		if swag.IsZero(m.Features[i]) { // not required
			continue
		}

		if m.Features[i] != nil {
			if err := m.Features[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("features" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var sVLocationListTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["FeatureCollection"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sVLocationListTypeTypePropEnum = append(sVLocationListTypeTypePropEnum, v)
	}
}

const (

	// SVLocationListTypeFeatureCollection captures enum value "FeatureCollection"
	SVLocationListTypeFeatureCollection string = "FeatureCollection"
)

// prop value enum
func (m *SVLocationList) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, sVLocationListTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SVLocationList) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SVLocationList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SVLocationList) UnmarshalBinary(b []byte) error {
	var res SVLocationList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
