// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jehiah/nyc_parking/internal/coord/models"
)

// GetByBoundsReader is a Reader for the GetByBounds structure.
type GetByBoundsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetByBoundsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetByBoundsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetByBoundsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetByBoundsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetByBoundsOK creates a GetByBoundsOK with default headers values
func NewGetByBoundsOK() *GetByBoundsOK {
	return &GetByBoundsOK{}
}

/*GetByBoundsOK handles this case with default header values.

Segments of all curbs within the bounding box, in arbitrary order.
*/
type GetByBoundsOK struct {
	Payload *models.SegmentRulesFeatureCollection
}

func (o *GetByBoundsOK) Error() string {
	return fmt.Sprintf("[GET /bybounds/all_rules][%d] getByBoundsOK  %+v", 200, o.Payload)
}

func (o *GetByBoundsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SegmentRulesFeatureCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByBoundsForbidden creates a GetByBoundsForbidden with default headers values
func NewGetByBoundsForbidden() *GetByBoundsForbidden {
	return &GetByBoundsForbidden{}
}

/*GetByBoundsForbidden handles this case with default header values.

This method requires an `access_key` and it is either missing or invalid, or the the credentials provided are not sufficient for access to the specified resource.
*/
type GetByBoundsForbidden struct {
	Payload *models.Error
}

func (o *GetByBoundsForbidden) Error() string {
	return fmt.Sprintf("[GET /bybounds/all_rules][%d] getByBoundsForbidden  %+v", 403, o.Payload)
}

func (o *GetByBoundsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByBoundsDefault creates a GetByBoundsDefault with default headers values
func NewGetByBoundsDefault(code int) *GetByBoundsDefault {
	return &GetByBoundsDefault{
		_statusCode: code,
	}
}

/*GetByBoundsDefault handles this case with default header values.

Unexpected error
*/
type GetByBoundsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get by bounds default response
func (o *GetByBoundsDefault) Code() int {
	return o._statusCode
}

func (o *GetByBoundsDefault) Error() string {
	return fmt.Sprintf("[GET /bybounds/all_rules][%d] get_by_bounds default  %+v", o._statusCode, o.Payload)
}

func (o *GetByBoundsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
