// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jehiah/nyc_parking/internal/coord/models"
)

// GetAtTimeByLocationReader is a Reader for the GetAtTimeByLocation structure.
type GetAtTimeByLocationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAtTimeByLocationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAtTimeByLocationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetAtTimeByLocationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAtTimeByLocationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAtTimeByLocationOK creates a GetAtTimeByLocationOK with default headers values
func NewGetAtTimeByLocationOK() *GetAtTimeByLocationOK {
	return &GetAtTimeByLocationOK{}
}

/*GetAtTimeByLocationOK handles this case with default header values.

Segments of all the curbs within the radius.
*/
type GetAtTimeByLocationOK struct {
	Payload *models.SegmentTimeFeatureCollection
}

func (o *GetAtTimeByLocationOK) Error() string {
	return fmt.Sprintf("[GET /bylocation/time_rules][%d] getAtTimeByLocationOK  %+v", 200, o.Payload)
}

func (o *GetAtTimeByLocationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SegmentTimeFeatureCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAtTimeByLocationForbidden creates a GetAtTimeByLocationForbidden with default headers values
func NewGetAtTimeByLocationForbidden() *GetAtTimeByLocationForbidden {
	return &GetAtTimeByLocationForbidden{}
}

/*GetAtTimeByLocationForbidden handles this case with default header values.

This method requires an `access_key` and it is either missing or invalid, or the the credentials provided are not sufficient for access to the specified resource.
*/
type GetAtTimeByLocationForbidden struct {
	Payload *models.Error
}

func (o *GetAtTimeByLocationForbidden) Error() string {
	return fmt.Sprintf("[GET /bylocation/time_rules][%d] getAtTimeByLocationForbidden  %+v", 403, o.Payload)
}

func (o *GetAtTimeByLocationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAtTimeByLocationDefault creates a GetAtTimeByLocationDefault with default headers values
func NewGetAtTimeByLocationDefault(code int) *GetAtTimeByLocationDefault {
	return &GetAtTimeByLocationDefault{
		_statusCode: code,
	}
}

/*GetAtTimeByLocationDefault handles this case with default header values.

Unexpected error
*/
type GetAtTimeByLocationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get at time by location default response
func (o *GetAtTimeByLocationDefault) Code() int {
	return o._statusCode
}

func (o *GetAtTimeByLocationDefault) Error() string {
	return fmt.Sprintf("[GET /bylocation/time_rules][%d] get_at_time_by_location default  %+v", o._statusCode, o.Payload)
}

func (o *GetAtTimeByLocationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
