// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAtTimeByBoundsParams creates a new GetAtTimeByBoundsParams object
// with the default values initialized.
func NewGetAtTimeByBoundsParams() *GetAtTimeByBoundsParams {
	var ()
	return &GetAtTimeByBoundsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAtTimeByBoundsParamsWithTimeout creates a new GetAtTimeByBoundsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAtTimeByBoundsParamsWithTimeout(timeout time.Duration) *GetAtTimeByBoundsParams {
	var ()
	return &GetAtTimeByBoundsParams{

		timeout: timeout,
	}
}

// NewGetAtTimeByBoundsParamsWithContext creates a new GetAtTimeByBoundsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAtTimeByBoundsParamsWithContext(ctx context.Context) *GetAtTimeByBoundsParams {
	var ()
	return &GetAtTimeByBoundsParams{

		Context: ctx,
	}
}

// NewGetAtTimeByBoundsParamsWithHTTPClient creates a new GetAtTimeByBoundsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAtTimeByBoundsParamsWithHTTPClient(client *http.Client) *GetAtTimeByBoundsParams {
	var ()
	return &GetAtTimeByBoundsParams{
		HTTPClient: client,
	}
}

/*GetAtTimeByBoundsParams contains all the parameters to send to the API endpoint
for the get at time by bounds operation typically these are written to a http.Request
*/
type GetAtTimeByBoundsParams struct {

	/*AccessKey
	  The API access key for the request.

	*/
	AccessKey string
	/*DurationH
	  If `primary_use` or `permitted_use` is set AND `duration_h` is set, only return
	segments that allow the given use for at least this long.


	*/
	DurationH *float64
	/*MaxLatitude
	  The largest latitude to return results for.

	*/
	MaxLatitude float64
	/*MaxLongitude
	  The largest longitude to return results for.

	*/
	MaxLongitude float64
	/*MinLatitude
	  The smallest latitude to return results for.

	*/
	MinLatitude float64
	/*MinLongitude
	  The smallest longitude to return results for.

	*/
	MinLongitude float64
	/*PermittedUse
	  If set, only return segments that permit this use at this time.

	*/
	PermittedUse *string
	/*PrimaryUse
	  If set, only return segments that have this primary use at this time.

	*/
	PrimaryUse *string
	/*Time
	  The time (in ISO-8601 format) to find the rules for. If not provided, we will use the current time.


	*/
	Time *strfmt.DateTime
	/*VehicleType
	  If `primary_use` or `permitted_use` is set AND `vehicle_type` is set, only return
	segments whose primary or permitted use, respectively, includes this vehicle type at
	this time. Setting `vehicle_type=all` will only return segments that permit every
	vehicle to engage in the use, while setting `primary_use` or `permitted_use`
	**without** setting `vehicle_type` returns segments that allow at least one kind of
	vehicle to engage in the use.


	*/
	VehicleType *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithTimeout(timeout time.Duration) *GetAtTimeByBoundsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithContext(ctx context.Context) *GetAtTimeByBoundsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithHTTPClient(client *http.Client) *GetAtTimeByBoundsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessKey adds the accessKey to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithAccessKey(accessKey string) *GetAtTimeByBoundsParams {
	o.SetAccessKey(accessKey)
	return o
}

// SetAccessKey adds the accessKey to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetAccessKey(accessKey string) {
	o.AccessKey = accessKey
}

// WithDurationH adds the durationH to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithDurationH(durationH *float64) *GetAtTimeByBoundsParams {
	o.SetDurationH(durationH)
	return o
}

// SetDurationH adds the durationH to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetDurationH(durationH *float64) {
	o.DurationH = durationH
}

// WithMaxLatitude adds the maxLatitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithMaxLatitude(maxLatitude float64) *GetAtTimeByBoundsParams {
	o.SetMaxLatitude(maxLatitude)
	return o
}

// SetMaxLatitude adds the maxLatitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetMaxLatitude(maxLatitude float64) {
	o.MaxLatitude = maxLatitude
}

// WithMaxLongitude adds the maxLongitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithMaxLongitude(maxLongitude float64) *GetAtTimeByBoundsParams {
	o.SetMaxLongitude(maxLongitude)
	return o
}

// SetMaxLongitude adds the maxLongitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetMaxLongitude(maxLongitude float64) {
	o.MaxLongitude = maxLongitude
}

// WithMinLatitude adds the minLatitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithMinLatitude(minLatitude float64) *GetAtTimeByBoundsParams {
	o.SetMinLatitude(minLatitude)
	return o
}

// SetMinLatitude adds the minLatitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetMinLatitude(minLatitude float64) {
	o.MinLatitude = minLatitude
}

// WithMinLongitude adds the minLongitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithMinLongitude(minLongitude float64) *GetAtTimeByBoundsParams {
	o.SetMinLongitude(minLongitude)
	return o
}

// SetMinLongitude adds the minLongitude to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetMinLongitude(minLongitude float64) {
	o.MinLongitude = minLongitude
}

// WithPermittedUse adds the permittedUse to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithPermittedUse(permittedUse *string) *GetAtTimeByBoundsParams {
	o.SetPermittedUse(permittedUse)
	return o
}

// SetPermittedUse adds the permittedUse to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetPermittedUse(permittedUse *string) {
	o.PermittedUse = permittedUse
}

// WithPrimaryUse adds the primaryUse to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithPrimaryUse(primaryUse *string) *GetAtTimeByBoundsParams {
	o.SetPrimaryUse(primaryUse)
	return o
}

// SetPrimaryUse adds the primaryUse to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetPrimaryUse(primaryUse *string) {
	o.PrimaryUse = primaryUse
}

// WithTime adds the time to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithTime(time *strfmt.DateTime) *GetAtTimeByBoundsParams {
	o.SetTime(time)
	return o
}

// SetTime adds the time to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetTime(time *strfmt.DateTime) {
	o.Time = time
}

// WithVehicleType adds the vehicleType to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) WithVehicleType(vehicleType *string) *GetAtTimeByBoundsParams {
	o.SetVehicleType(vehicleType)
	return o
}

// SetVehicleType adds the vehicleType to the get at time by bounds params
func (o *GetAtTimeByBoundsParams) SetVehicleType(vehicleType *string) {
	o.VehicleType = vehicleType
}

// WriteToRequest writes these params to a swagger request
func (o *GetAtTimeByBoundsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param access_key
	qrAccessKey := o.AccessKey
	qAccessKey := qrAccessKey
	if qAccessKey != "" {
		if err := r.SetQueryParam("access_key", qAccessKey); err != nil {
			return err
		}
	}

	if o.DurationH != nil {

		// query param duration_h
		var qrDurationH float64
		if o.DurationH != nil {
			qrDurationH = *o.DurationH
		}
		qDurationH := swag.FormatFloat64(qrDurationH)
		if qDurationH != "" {
			if err := r.SetQueryParam("duration_h", qDurationH); err != nil {
				return err
			}
		}

	}

	// query param max_latitude
	qrMaxLatitude := o.MaxLatitude
	qMaxLatitude := swag.FormatFloat64(qrMaxLatitude)
	if qMaxLatitude != "" {
		if err := r.SetQueryParam("max_latitude", qMaxLatitude); err != nil {
			return err
		}
	}

	// query param max_longitude
	qrMaxLongitude := o.MaxLongitude
	qMaxLongitude := swag.FormatFloat64(qrMaxLongitude)
	if qMaxLongitude != "" {
		if err := r.SetQueryParam("max_longitude", qMaxLongitude); err != nil {
			return err
		}
	}

	// query param min_latitude
	qrMinLatitude := o.MinLatitude
	qMinLatitude := swag.FormatFloat64(qrMinLatitude)
	if qMinLatitude != "" {
		if err := r.SetQueryParam("min_latitude", qMinLatitude); err != nil {
			return err
		}
	}

	// query param min_longitude
	qrMinLongitude := o.MinLongitude
	qMinLongitude := swag.FormatFloat64(qrMinLongitude)
	if qMinLongitude != "" {
		if err := r.SetQueryParam("min_longitude", qMinLongitude); err != nil {
			return err
		}
	}

	if o.PermittedUse != nil {

		// query param permitted_use
		var qrPermittedUse string
		if o.PermittedUse != nil {
			qrPermittedUse = *o.PermittedUse
		}
		qPermittedUse := qrPermittedUse
		if qPermittedUse != "" {
			if err := r.SetQueryParam("permitted_use", qPermittedUse); err != nil {
				return err
			}
		}

	}

	if o.PrimaryUse != nil {

		// query param primary_use
		var qrPrimaryUse string
		if o.PrimaryUse != nil {
			qrPrimaryUse = *o.PrimaryUse
		}
		qPrimaryUse := qrPrimaryUse
		if qPrimaryUse != "" {
			if err := r.SetQueryParam("primary_use", qPrimaryUse); err != nil {
				return err
			}
		}

	}

	if o.Time != nil {

		// query param time
		var qrTime strfmt.DateTime
		if o.Time != nil {
			qrTime = *o.Time
		}
		qTime := qrTime.String()
		if qTime != "" {
			if err := r.SetQueryParam("time", qTime); err != nil {
				return err
			}
		}

	}

	if o.VehicleType != nil {

		// query param vehicle_type
		var qrVehicleType string
		if o.VehicleType != nil {
			qrVehicleType = *o.VehicleType
		}
		qVehicleType := qrVehicleType
		if qVehicleType != "" {
			if err := r.SetQueryParam("vehicle_type", qVehicleType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
